apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: unbi4hb12-nodejs 
  janus-idp.io/tekton: unbi4hb12-nodejs
  backstage.io/kubernetes-id: unbi4hb12-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: unbi4hb12-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml