apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: unbi4hb12-nodejs
  janus-idp.io/tekton: unbi4hb12-nodejs
  backstage.io/kubernetes-id: unbi4hb12-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: unbi4hb12-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
